
package services.weather_service_two;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.meteoservices.weather_service_two.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherPort", targetNamespace = "http://services/weather_service_two")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherPort {


    /**
     * 
     * @param getWeatherRequest
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(name = "getWeatherResponse", targetNamespace = "http://meteoservices.com/weather_service_two", partName = "getWeatherResponse")
    public Object getWeather(
        @WebParam(name = "getWeatherRequest", targetNamespace = "http://meteoservices.com/weather_service_two", partName = "getWeatherRequest")
        Object getWeatherRequest);

}
