
package services.weather_service_three;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherPortService", targetNamespace = "http://services/weather_service_three", wsdlLocation = "http://localhost:8080/ws/weather.wsdl")
public class WeatherPortService
    extends Service
{

    private final static URL WEATHERPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERPORTSERVICE_EXCEPTION;
    private final static QName WEATHERPORTSERVICE_QNAME = new QName("http://services/weather_service_three", "WeatherPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/weather.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERPORTSERVICE_WSDL_LOCATION = url;
        WEATHERPORTSERVICE_EXCEPTION = e;
    }

    public WeatherPortService() {
        super(__getWsdlLocation(), WEATHERPORTSERVICE_QNAME);
    }

    public WeatherPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERPORTSERVICE_QNAME, features);
    }

    public WeatherPortService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERPORTSERVICE_QNAME);
    }

    public WeatherPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERPORTSERVICE_QNAME, features);
    }

    public WeatherPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherPort
     */
    @WebEndpoint(name = "WeatherPortSoap11")
    public WeatherPort getWeatherPortSoap11() {
        return super.getPort(new QName("http://services/weather_service_three", "WeatherPortSoap11"), WeatherPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherPort
     */
    @WebEndpoint(name = "WeatherPortSoap11")
    public WeatherPort getWeatherPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/weather_service_three", "WeatherPortSoap11"), WeatherPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERPORTSERVICE_EXCEPTION!= null) {
            throw WEATHERPORTSERVICE_EXCEPTION;
        }
        return WEATHERPORTSERVICE_WSDL_LOCATION;
    }

}
